### ISSUE TITLE
Does not validate JSON

### ISSUE THREAD

**Issue by eccles** [python-openapi/openapi-spec-validator#200]
Surprisingly invalid JSON will validate - specifically trailing commas on last entry of a list.

So whilst this package does validate openapi, it does not check basic json ... Ironically this failure happened when adding an endpoit that emitted the openapi:

```    },
    "/endpoint/openapi": {
      "get": {
        "summary": "Get OpenAPI spec for Endpoint",
        "description": "Get OpenAPI v2.0 spec for Endpoint",
        "operationId": "Endpoint_API",
        "responses": {
          "200": {
            "description": "A successful response."
          },
          "401": {
            "description": "Returned when the user is not authenticated to the system."
          },
          "429": {
            "description": "Returned when a user exceeds their subscription's rate limit for requests."
          }
        },
        "tags": [
          "Endpoint"
        ]
      }
    },
  },
```
Second last line has trailing comma which is incorrect json but passed validation.

**Comment by p1c2u** [comment]
Hi @eccles,

That's totally fine. OpenAPI specification doesn't need to be valid JSON. Actually YAML 1.2 is recommended for the specification and, because JSON is actually a subset of YAML, OpenAPI specification document can be valid YAML but at the same time can be invalid JSON.

> YAML version [1.2](https://yaml.org/spec/1.2/spec.html) is RECOMMENDED along with some additional constraints

https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#format
